spring.application.name=fx-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/fx_prueba
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true